// js/tableNameMap.js
const tableNameMap = {
    Admin: "管理員",
    BookAndReport: "書籍與報告",
    BookPaper: "專書論文",
    ConferencePaper: "會議論文",
    Course: "課程",
    CSDepartment: "資工系",
    Department: "系所",
    DepartmentHead: "系主任",
    Education: "學歷",
    Expertise: "專長",
    ExternalAward: "校外獲獎",
    ExternalExperience: "校外經歷",
    IndustryProject: "產學合作計畫",
    InternalAward: "校內獲獎",
    InternalExperience: "校內經歷",
    Introduction: "自我介紹",
    JournalPublication: "期刊論文",
    Lecture: "演講記錄",
    MainPageBannerPicture: "首頁橫幅圖片",
    NSCProject: "國科會計畫",
    Patent: "專利",
    Professor: "教授",
    Staff: "職員",
    User: "使用者"
};
